# Generated by Django 5.2 on 2026-01-14 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1, 'Сообщение не может быть пустым')], verbose_name='Название'),
        ),
    ]
